### ISSUE TITLE
Watcher Inotify is crashing on repository init

### ISSUE THREAD

**Issue by bpereto** [bpereto/borg-hive#1]
Watcher crashes on repository create:
`borg init --encryption=repokey-blake2 bqs6jumh@localhost:test4`

```
watcher_1  | Call failed (should not be -1): (-1) ERRNO=(0)
watcher_1  | Traceback (most recent call last):
watcher_1  |   File "/app/borghive/management/commands/watch_repositories.py", line 51, in handle
watcher_1  |     for event in i.event_gen(yield_nones=False):
watcher_1  |   File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 300, in event_gen
watcher_1  |     self._i.add_watch(full_path, self._mask)
watcher_1  |   File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 95, in add_watch
watcher_1  |     wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
watcher_1  |   File "/usr/local/lib/python3.8/site-packages/inotify/calls.py", line 34, in _check_nonnegative
watcher_1  |     raise InotifyError("Call failed (should not be -1): (%d)" %
watcher_1  | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
```

**Comment by ikkemaniac** [comment]
I've ran into this too, any idea on the cause for this?

**Comment by bpereto** [comment]
Not at the moment. I want to check if it's happening also on k8s. 
Could be a namespacing issues in docker / linux. Searching the Web doesn't give much more information about it.

**Comment by bpereto** [comment]
I don't experience this on k8s with the following setup:
* Centos8 4.18.0-193.28.1.el8_2.x86_64
* docker-ce-19.03.13-3.el7.x86_64
* K8s: v1.19.3
