### ISSUE TITLE
BorgWatcher: Error -1

### ISSUE THREAD

**Issue by Firesphere** [bpereto/borg-hive#77]
BorgWatcher keeps throwing this error:
```
Traceback (most recent call last):
  File "/app/borghive/management/commands/watch_repositories.py", line 55, in handle
    for event in i.event_gen(yield_nones=False):
  File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 300, in event_gen
    self._i.add_watch(full_path, self._mask)
  File "/usr/local/lib/python3.8/site-packages/inotify/adapters.py", line 95, in add_watch
    wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
  File "/usr/local/lib/python3.8/site-packages/inotify/calls.py", line 34, in _check_nonnegative
    raise InotifyError("Call failed (should not be -1): (%d)" %
inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
```

According to the internet, it's because the limit on inotify... I've upped this to the max, but it keeps happening... Any idea?

**Comment by Firesphere** [comment]
This might be related to
https://github.com/bpereto/borg-hive/issues/1
